name: build on commit

on:
  push:
    branches:
      - main
    paths-ignore:
      - "build/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone repository
        uses: actions/checkout@v6

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
      
      - name: npm install dependencies
        run: npm i

      - name: vite build
        run: npm run build

      - name: commmit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add build
          git commit -m "automated build"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
